vouformar/config/routes.rb
Rails.application.routes.draw do
  resources :grids
  resources :disciplines
  resources :disciplines
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  

  root 'sessions#new'

end

vouformar/app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
end

vouformar/app/models/admin.rb
class Admin < User
end

vouformar/app/models/admin_facade.rb
class AdminFacade < ActiveRecord::Base
end

vouformar/app/models/authenticate.rb
class Authenticate < ActiveRecord::Base
end

vouformar/app/models/course.rb
class Course < AbstractCourse
	has_one :emphasis
end

vouformar/app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  has_many :AbstractDiscipline
end

vouformar/app/models/department.rb
class Department < ActiveRecord::Base
  has_many :AbstractDiscipline

  validates_presence_of :name, message: "O nome é obrigatório"
  validates_presence_of :code, message: "o Codigo do departamento é obrigatório"
  validates_numericality_of :code, message: "Somente numeros"
end

vouformar/app/models/discipline.rb
class Discipline < ActiveRecord::Base
	belongs_to :grid
end

vouformar/app/models/emphasis.rb
class Emphasis < AbstractCourse
	 belongs_to :course
end

vouformar/app/models/grid.rb
class Grid < ActiveRecord::Base
	has_many :discipline
	serialize :discipline_id
end

vouformar/app/models/pre_requisite.rb
class PreRequisite < ActiveRecord::Base
  belongs_to :AbstractDiscipline
end

vouformar/app/models/progress.rb
class Progress < ActiveRecord::Base
end

vouformar/app/models/session.rb
class Session < ActiveRecord::Base

validates_presence_of :registration, message: "Matricula é obrigatório"
	validates_numericality_of :registration, message: "Somente numeros" #pesquisar validação da matricula
	validates_length_of :registration, :maximum => 9, message: "Tamanho invalido"

  has_secure_password

	  validates :password,	:presence => true,
                       		:confirmation => true,
                       		:length => {:within => 6..40},
                       		:on => :create

    validates :password_confirmation,	:presence => true,
                       		:confirmation => true,
                       		:length => {:within => 6..40},
                       		:on => :create
end

vouformar/app/models/sessions.rb
class Session < ActiveRecord::Base

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, message: "Formato invalido"
	validates_presence_of :email, message: "Email é obrigatório"
	validates_uniqueness_of :email, message: "Email existente"


	has_secure_password

	validates_presence_of :password, message: "Senha é obrigatório"
	validates_confirmation_of :password
	validates_length_of :password, :within => 6..40, message: "Mínimo 6 digitos"
end

vouformar/app/models/student.rb
class Student < User

	validates_presence_of :registration, message: "Matricula é obrigatório"
	validates_uniqueness_of :registration, message: "Matricula existente"
	validates_numericality_of :registration, message: "Somente numeros" #pesquisar validação da matricula
	validates_length_of :registration, :maximum => 9, message: "Máximo 9 digitos"

	validates :year_registration, 
	inclusion: {
		in: 2000..Date.today.year, 
		message: "Ano invalido" 
	},
	format: { 
		with: /(20)\d{2}/i, 
		message: "Formato invalido"
	}
	validates_presence_of :year_registration, message: "O ano de Ingresso é obrigatório"

end

vouformar/app/models/user.rb
class User < ActiveRecord::Base
	has_one :address

	before_save { self.email = email.downcase }

	accepts_nested_attributes_for :address, allow_destroy: true

	validates_length_of :name, :maximum => 50, message: "Máximo 50 caracteres."
	validates_format_of :name, :with => /[A-Za-z]/, :on => :create, message: "Formato inválido"

	validates_length_of :last_name, :maximum => 50, message: "Máximo 50 caracteres"
	#validates_format_of :last_name, :with => /[A-Za-z]/, :on => :create, message: "Formato invalido"

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, message: "Formato invalido"
	validates_presence_of :email, message: "Email é obrigatório"
	validates_uniqueness_of :email, message: "Email existente"

	validates_cpf :cpf_attr

	has_secure_password

	validates_presence_of :password, :on => :create, message: "Senha é obrigatório"
	validates_confirmation_of :password, :on => :create
	validates_length_of :password, :within => 6..40, :on => :create, message: "Mínimo 6 digitos"

	validates_presence_of :password_confirmation, :on => :create, message: "Confirmar Senha é obrigatório"
	validates_confirmation_of :password_confirmation, :on => :create
	validates_length_of :password_confirmation, :within => 6..40, :on => :create

	validates_confirmation_of :password, :allow_blank => true, :allow_nil => true, :on => :update
	validates_length_of :password, :within => 6..40, :allow_blank => true, :allow_nil => true, :on => :update, message: "Mínimo 6 digitos"

	validates_confirmation_of :password_confirmation, :allow_blank => true, :allow_nil => true, :on => :update
	validates_length_of :password_confirmation, :within => 6..40, :allow_blank => true, :allow_nil => true, :on => :update

#implementar autenticação de usuario aqui

	def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
  	end
end

vouformar/app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  before_action :need_be_logged

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:code, :name, :description, :credits, :prerequisites)
    end
end

vouformar/app/helpers/admin_helper.rb
module AdminHelper
end

vouformar/app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

vouformar/app/helpers/form_helper.rb
module FormHelper
  def setup_user(user)
    user.address ||= Address.new
    user
  end
end

vouformar/app/helpers/grid_helper.rb
module GridHelper
end

vouformar/app/helpers/grids_helper.rb
module GridsHelper
end

vouformar/app/helpers/users_helper.rb
module UsersHelper
end

vouformar/app/views/disciplines/_form.html.erb
<%= form_for(@discipline) do |f| %>
  <% if @discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% @discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :credits %><br>
    <%= f.number_field :credits %>
  </div>
  <div class="field">
    <%= f.label :prerequisites %><br>
    <%= f.text_field :prerequisites %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vouformar/app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form' %>

<%= link_to 'Show', @discipline ,:class => "btn btn-success"%> 
<%= link_to 'Back', disciplines_path, :class => "btn btn-danger"%>

vouformar/app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Disciplines</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Credits</th>
      <th>Prerequisites</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.code %></td>
        <td><%= discipline.name %></td>
        <td><%= discipline.prerequisites %></td>
        <td><%= link_to 'Show', discipline %></td>
        <td><%= link_to 'Edit', edit_discipline_path(discipline) %></td>
        <td><%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discipline', new_discipline_path %>

vouformar/app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplines_path %>

vouformar/app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @discipline.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @discipline.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @discipline.description %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @discipline.credits %>
</p>

<p>
  <strong>Prerequisites:</strong>
  <%= @discipline.prerequisites %>
</p>

<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<%= link_to 'Back', disciplines_path %>